### ISSUE TITLE
Allow different sorting methods for badges.

### ISSUE THREAD

**Issue by oddshocks** [fedora-infra/tahrir#122]
This isn't urgent, but we could add a few buttons to the user view so that you can sort badges by id, name, or whatever. For now, I'm fixing #120 by sorting the badges by id.

**Comment by ralphbean** [comment]
I'm going to call this closed now that #301 is merged, released, and deployed.  It's not multiple sorting methods, but it *is* a much more reasonable way to view existing badges.
