### ISSUE TITLE
Badge collage.

### ISSUE THREAD

**Issue by oddshocks** [fedora-infra/tahrir#129]
@jamielinux had the cool idea of a page where all the badges would be displayed in a big ol' pile. Users could spot badges that they think are cool, and mouseover or click on them to learn about their criteria and go for them.

I think this is an awesome idea, and would also be quite visually tasty.

**Comment by ralphbean** [comment]
Reading this again.  I think it already exists with the ``/explore`` page, no?

I'll go ahead and close.  Re-open if there is a different vision here.
