### ISSUE TITLE
Trivial: Odd times on Latest Awards.

### ISSUE THREAD

**Issue by oddshocks** [fedora-infra/tahrir#130]
With the new websocket stuff, there's some odd time-ordering stuff happening with badges that have just been awarded. So far I've seen:

- ``was awarded 1 sec from now`` (future badge! :space_invader:)
- ``just now`` ending up below ``1 second ago``

This isn't a big deal, but I'm opening a ticket so that the issue is documented.

**Comment by oddshocks** [comment]
@ralphbean, hasn't this been fixed? I remember the "four hours from now" thing...

**Comment by ralphbean** [comment]
Ah!  This was probably due to clock skew on our servers which got fixed here:  https://fedorahosted.org/fedora-infrastructure/ticket/4646!

Thanks :)
