### ISSUE TITLE
Email address is "wrong" in Fedora Badges

### ISSUE THREAD

**Issue by langdon** [fedora-infra/tahrir#161]
My fedora account is not attached to any groups. As a result, my fedorapeople.org email address is not active. However, on my badges profile page that email address is displayed, and, I think, linked to "my account" at openbadges.

**Comment by agriffis** [comment]
"I'm sorry to say this won't be changed in the near future. The backpack is being maintained, but new features aren't being added for the foreseeable future. It's essentially in maintenance mode." from mozilla/openbadges-backpack#42

**Comment by szydell** [comment]
Mozilla backpack has the ability to add more than one e-mail address. But this does not solve the problem, because e-mail needs to be verified.
When @fedoraproject.org alias is not active, you cannot use it on the backpack profile.
