### ISSUE TITLE
"4 hours from now" bug

### ISSUE THREAD

**Issue by oddshocks** [fedora-infra/tahrir#257]
I awarded 3 of the same badge to 3 different people within 1 minute on badges.rit.edu and the last two came up as being awarded "4 hours from now":
![hours_from_now](https://f.cloud.github.com/assets/1376599/2089761/330c4608-8e8b-11e3-8efb-a4c91ab3f846.png)

**Comment by bochecha** [comment]
Just got this issue with the devconf badge:

![45 seconds from now](https://cloud.githubusercontent.com/assets/272170/6091797/cb2a38fc-aebd-11e4-920f-5866228a83af.png)

What I did was:
* Go to bit.ly/devconf2015
* Log in when requested
* I was redirected to the page shown in the screenshot

**Comment by ralphbean** [comment]
First thing I think is to check the consistency of the system time between our servers (badges backend, badges web, and datagrepper).  I hit an issue the other day where our github2fedmsg server was 4 minutes behind the notifications server, which caused a similar discrepancy.

**Comment by ralphbean** [comment]
Perhaps related -> https://fedorahosted.org/fedora-infrastructure/ticket/4646
