### ISSUE TITLE
Curious Penguin (Ask Fedora) badges not counting all answers

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/tahrir#288]
According to my [ask.fpo profile](https://ask.fedoraproject.org/en/users/9471/qulogic/), I have answered 19 questions. But I have _not_ been awarded [Curious Penguin (Ask Fedora II)](https://badges.fedoraproject.org/badge/curious-penguin-ask-fedora-ii) which is supposed to be 10+.

I think the problem is that the counting does not take into account the linked login methods. I originally used Google+ to login to ask.fpo, and later added on the FAS login. This didn't trigger any badges, so I figured it would not happen until I did something with the linked account. But when I answered something, it only triggered the Ask Fedora I badge.

**Comment by ralphbean** [comment]
Right, we just don't have that level of integration.  Once you linked your accounts, all future activity is counted but activity before that -- well, we just don't have a way to extract it beyond writing some very specific code to query the ask.fpo database.

The badges awarder gets its count of event from the ![datanommer/datagrepper system](https://apps.fedoraproject.org/datagrepper/raw?user=qulogic) and you can see the count of ask.fpo activity of yours that it knows about ![here](https://apps.fedoraproject.org/datagrepper/raw?user=qulogic&category=askbot).

With respect, I'd like to close this as ``wontfix``.  Writing code to query the ask.fpo database directly will be fragile.  There are updates to that system that come from another upstream, and our integration code there would break easily over time (as they change the way that they model linked accounts, etc).
