### ISSUE TITLE
Choosing an email address

### ISSUE THREAD

**Issue by aleksandar-todorovic** [fedora-infra/tahrir#309]
So, I already have a Mozilla Backpack account, but once I tried to export my Fedora badges to it, I realized that those badges were not issued to the email address I used to sign up for my user profile. Instead of, they had been issued to `USERNAME@fedoraproject.org`.

Is there any way to change this? I would really like to have one unified Mozilla Backpack containing all of my badges. This kind of makes that complicated.

**Comment by pypingou** [comment]
I think this is a duplicate of : https://github.com/fedora-infra/tahrir/issues/161

**Comment by aleksandar-todorovic** [comment]
Yes it is! Sorry about that.
