### ISSUE TITLE
helping-hands badge does not work properly

### ISSUE THREAD

**Issue by robyduck** [fedora-infra/tahrir#315]
I noticed the helping-hands badge is not working as it should, actually. Since some time ago the badge got awarded correctly, if you build a package which you do not own.
Since a few weeks this badge gets awarded to users who build their own package, not sure with which criteria.
Some examples:
jsmith builds pixman, https://apps.fedoraproject.org/datagrepper/id?id=2014-91e152fc-2ed8-44a3-99c0-e7e58bc3a104&is_raw=true&size=extra-large and the owner is ajax, correct.

sandeeps builds woffTools, https://apps.fedoraproject.org/datagrepper/id?id=2015-bbca1d27-e8f3-4c5d-87dc-f9b68bf27b65&is_raw=true&size=extra-large and the owner is sandeeps, not correct.

I saw this because I build onionshare, and I'm the co-maintainer of that package which is owned by pjp. No badge awarded, so I looked into it a bit more.

I saw the YML, but it looks ok to me, not sure where the issue could be.

**Comment by ralphbean** [comment]
I'm not sure what's going on.  I dug into the code in fedbadges/rules.py and fedbadges/utils.py, but initial hand testing suggests it is all working fine.

I added some debug statements to production.  Let's wait until it happens again and see what the logs say.

https://apps.fedoraproject.org/datagrepper/raw?category=fedbadges&contains=helping-hand&delta=1278000

**Comment by ralphbean** [comment]
Ah ha!  I got this in the logs:

```
[u'cpufrequtility'] not subset of set([u'CPUFreqUtility', u'kde-plasma-alsa-volume', u'se-sandbox-runner', u'pyqt-mail-checker', u'sandbox-runner-data'])
```

Forcing everything lowercase there should help.

**Comment by frafra** [comment]
I don't know if it's strictly related, but I co-maintain autotrash (owned by robyduck), I built it and I pushed an update with Bodhi, but I got no badge.

https://apps.fedoraproject.org/datagrepper/id?id=2015-f2635359-6649-44a6-85f0-5c551ed858b1&is_raw=true&size=extra-large
