### ISSUE TITLE
Is there a cron script for the Mugshot badge?

### ISSUE THREAD

**Issue by alxpl** [fedora-infra/tahrir#316]
If yes, how often does it run? I was fiddling with libravatar yesterday and decided to add an avatar to my FAS account (alexpl) but Datagrepper doesn't mention it and I have not been awarded the badge yet :(

**Comment by ralphbean** [comment]
There is.  The badges we award by cron are all [defined here](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/badges/backend/files/cron).  It looks like it run every 2 hours.. and it takes quite a while to complete.  It just started up 20 minutes ago.  Let us know if it doesn't award it to you anytime soon.

**Comment by alxpl** [comment]
I have just received the badge. If the script runs every two hours, it must have skipped me at least 9 times, so you might want to look into that.
Thanks for the link and for the information.

**Comment by jflory7** [comment]
For clarification to the above, it was discovered that the cron script actually runs every two days, not every two hours.

`[13:21:32] <threebean> oh, well, it looks like the cronjob runs every 2 hours, actually https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/badges/backend/files/cron/award-libravatar-badge.cron`
