### ISSUE TITLE
Baby Badger badge not awarded on first login

### ISSUE THREAD

**Issue by jwflory** [fedora-infra/tahrir#317]
The [Baby Badger](https://badges.fedoraproject.org/badge/baby-badger) badge is awarded to users on their first login to the Badges site. I noticed recently that [my account](https://badges.fedoraproject.org/user/jflory7) was not awarded this badge when I first logged into the Badges site close to a year and a half ago.

If I had to suspect a particular reason, it looks like my Badges account "arrived" on 1-01-2014. If I recall correctly, I had made my account just a little bit past the New Year - I know that servers sometimes like to act up when big things happen like year changes / daylight savings time / etc., so perhaps this might be the root cause of the issue. If Badges accounts can be queried, other users who joined on the first day of a new year should also be checked to see if the issue is more widespread than just my account.

**Comment by ralphbean** [comment]
Badge [awarded to jflory7](https://apps.fedoraproject.org/datagrepper/id?id=2015-e6d8aa70-fd0b-4d07-8fcf-b4542fc60866&is_raw=true&size=extra-large).

Note that 1) having your account created in the badges system and 2) logging in (which is what the baby-badger badge is for) -- are not the same thing.  So, just looking at when the accounts were created won't do it.  We *can* however look to see if the [last_login](https://github.com/fedora-infra/tahrir-api/blob/develop/tahrir_api/model.py#L120) field is not ``null``, and award the badge to all those people.

**Comment by jflory7** [comment]
Okay, makes sense. In that case, I'm not sure when I first logged into the Badges app directly… it's been a while. It seems like it has been awarded correctly prior and after that point, so for all practical reasons, it seems to be working. Maybe a server or service was having issues that day or something. Anyways, thanks!

**Comment by vwbusguy** [comment]
I can verify this bug as well.  My badges profile: https://badges.fedoraproject.org/user/vwbusguy

**Comment by vwbusguy** [comment]
Just want to verify- I still don't have this badge, but it clearly showed up in in the Fedora notifier:

https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.fedbadges.person.login.first&user=vwbusguy&rows_per_page=1

**Comment by dhanvi** [comment]
I am also effected by the same issue here is my profile https://badges.fedoraproject.org/user/dhanvi
