### ISSUE TITLE
Delivery badge not awarded

### ISSUE THREAD

**Issue by alxpl** [fedora-infra/tahrir#318]
Hi again,

After the Mugshot issue, I started paying _a little more_ attention and I've just noticed that I'm missing a delivery badge. Are these awarded automatically or manually? Could it be that the host on which the scripts run hates me?

Cheers
Alex

**Comment by ralphbean** [comment]
Let's see, [here's the badge](https://badges.fedoraproject.org/badge/delivery) and [here's the rule that awards it](https://git.fedorahosted.org/cgit/badges.git/tree/rules/pkgdb-hatchling-i.yml).  Here are [all the messages that trigger it](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.pkgdb.package.new).

I see your [packages here in pkgdb](https://admin.fedoraproject.org/pkgdb/packager/alexpl/).  What package did you add, and when?

**Comment by alxpl** [comment]
Well, datagrepper yields nothing when I add my user name (https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.pkgdb.package.new&user=alexpl), but I added gdouros-anaktoria-fonts, gdouros-aroania-fonts and gdouros-asea-fonts in late July:
https://bugzilla.redhat.com/show_bug.cgi?id=1228865
https://bugzilla.redhat.com/show_bug.cgi?id=1228868
https://bugzilla.redhat.com/show_bug.cgi?id=1228869
Any guesses as to what went wrong?

**Comment by alxpl** [comment]
I finally got some time to do a little bit of digging from my side of things. I suspect that timestamps in a package timeline and the ones reported by datagrepper should always be identical (at least I haven't stumbled upon a mismatch), for instance:
https://admin.fedoraproject.org/pkgdb/package/envytools/timeline
and
https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.pkgdb.package.new&package=envytools

This is the timeline for gdouros-anaktoria-fonts:
https://admin.fedoraproject.org/pkgdb/package/gdouros-anaktoria-fonts/timeline
and this is a datagrepper query for the same package:
https://apps.fedoraproject.org/datagrepper/raw?package=gdouros-anaktoria-fonts

Notice that the branches and everything were created from 16:54:19 to 16:54:29. Datagrepper shows nothing during that same span - the previous entry starts at 16:53:11 and the next one at 16:55:30.
Also, since Kevin was the one to introduce the package in pkgdb, this should be visible in a query combining the new package filter and his user name:
https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.pkgdb.package.new&user=kevin
Yet, there's nothing there.

Another interesting bit, the query for gdouros-anaktoria-fonts does not contain any pkgdb.acl.update messages. For the sake of comparison, look again at envytools:
https://apps.fedoraproject.org/datagrepper/raw?package=envytools

Could the fact that these fonts share the same source (TextFonts.zip) with a pre-existing package (gdouros-alexander-fonts) play any part?

**Comment by kavol** [comment]
just FYI, I have the same problem

not counting older packages, since this bug has been reported, I've added comic-neue-fonts on 2015-12-02 and horai-ume-fonts on 2016-04-26, and still I don't have the delivery badge :-(
