### ISSUE TITLE
Libravatar badge not being awarded

### ISSUE THREAD

**Issue by Keerthana17** [fedora-infra/tahrir#319]
Not getting a libravatar badge although my accounts are connected... :(

**Comment by ralphbean** [comment]
What's your FAS username?

**Comment by pollei** [comment]
I also didn't get badge and I'm pretty sure my avatar didn't get used. http://spollei.id.fedoraproject.org/

**Comment by pollei** [comment]
I also didn't get a badge for my avatar . https://badges.fedoraproject.org/user/spollei

**Comment by pollei** [comment]
I just got my MugShoot badge, thanks

**Comment by ralphbean** [comment]
Thanks for letting us know.  It just takes a long time.  The script that checks for new libravatar images only runs [once every two days](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/badges/backend/files/cron/award-libravatar-badge.cron).

**Comment by Keerthana17** [comment]
Hey Ralph,
Sorry, the feed from this issue accidently went to my spam. Yeah, I checked
and you're right, I did get the badge after two days. Thanks for clearing
that up. Sorry for the delay in the reply.
Keerthana

On 2 November 2015 at 01:33, Ralph Bean <notifications@github.com> wrote:

> Thanks for letting us know. It just takes a long time. The script that
> checks for new libravatar images only runs once every two days
> <https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/badges/backend/files/cron/award-libravatar-badge.cron>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fedora-infra/tahrir/issues/319#issuecomment-152858882>
> .
>



-- 
Keerthana Krishnan
B.Tech Computer Science (2012-16)
Govt. Model Engineering College
Email : contactkeerthana@gmail.com
IEEE CS Student Member
Blogger : https://cutencrazyindie.wordpress.com/
