### ISSUE TITLE
Karma badges broken ("What goes around comes around")

### ISSUE THREAD

**Issue by frozencemetery** [fedora-infra/tahrir#330]
As far as I can tell, these haven't worked since mid-August according to https://badges.fedoraproject.org/badge/what-goes-around-comes-around-karma-i

My FAS ID is rharwood; [my bodhi page](https://bodhi.fedoraproject.org/users/rharwood).

Thanks!

**Comment by ralphbean** [comment]
Nice catch.  I just pushed out a [fix] to the badge rules which should help.  Can you let me know if you receive the badge(s) the next time you get a comment on an update of yours?

**Comment by frozencemetery** [comment]
Willdo.  Thanks!

**Comment by frozencemetery** [comment]
It seems to be working again!  It was a nice touch that it noticed that I also met the requirements for ii and issued me that as well.

Thanks again!
