### ISSUE TITLE
fedora-badge account question

### ISSUE THREAD

**Issue by st-isidore-de-seville** [fedora-infra/tahrir#331]
I apologize in advance as I could not find this on the site.  How can I remove my fedora-badge account?

Thanks.

**Comment by ralphbean** [comment]
There should be a 'disable' button on your profile on https://badges.fedoraproject.org/ if you login there.  Do you see it?

**Comment by sayanchowdhury** [comment]
@st-isidore-de-seville I am closing this issue. If you have questions, feel free to re-open the issue.
