### ISSUE TITLE
"Go Back" on "this activity" page is not working

### ISSUE THREAD

**Issue by trishnaguha** [fedora-infra/tahrir#332]
Clicking on `this activity` of a badge earned from `History` by default opens the raw data/datagrepper page in a new tab, when I click on the option `Go Back` of the datagrepper page it doesn't take me back to `user` page. 

Suppose for my username, https://badges.fedoraproject.org/user/trishnag when I click on `this activity` of one of the badges earned, the datagrepper page opens in a new tab. And when I click on `Go Back` of the datagrepper page, it stays on the same page. It should take me back to https://badges.fedoraproject.org/user/trishnag

So we can avoid `this activity` page i.e, the `datagrepper` data opening by default in a new tab. This might fix the issue?

**Comment by pypingou** [comment]
But if you just close the newly opened tab, you're back on the page where you were, no?

Opening in a new tab will of course break the "back" action, since history is stored per tab and this tab is brand new. However, just closing the tab should bring you back to where you were, no?

**Comment by ralphbean** [comment]
There is a "go back" link on the datagrepper page for looking at an individual message.  I'm not sure it was ever working -- we should probably just remove it.

**Comment by trishnaguha** [comment]
@pypingou Yes I can do that :) . 
@pypingou @ralphbean I wanted to say, suppose if we see [[1]](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.irc.karma) https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.irc.karma when we click on `JSON` of any of the messages, it opens the raw data page on the same tab. So when we click on `Go Back` of the page it takes us back to [[1]](https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.irc.karma) . The same we can do with `this activity` of badges earned ? i.e, opening the raw data page of `this activity` on the same tab, therefore `Go Back` will also make sense.

I am not sure if this will break any code. I also want to know that will you like opening the raw data page on the same tab? :)
