### ISSUE TITLE
devconf-2015-attendee icon does not show up

### ISSUE THREAD

**Issue by kparal** [fedora-infra/tahrir#334]
The icon does not up at https://badges.fedoraproject.org/badge/devconf-2015-attendee and when you look at https://badges.fedoraproject.org/pngs/devconf2015.png directly, it returns HTML code, not PNG.

**Comment by ralphbean** [comment]
Looks like the wrong data was imported into the badges assets repo.

@nbebout, @cydrobolt.  Would either of you like to take a look at this?

**Comment by cydrobolt** [comment]
I can take a look at this later today.

**Comment by cydrobolt** [comment]
Fixed. Seems like there was something wrong with the file locally in the `/git/badges` repository. The `git pull`s from the `push-badges.yml` didn't fix the issue automatically because `git pull` doesn't overwrite local changes.

:+1:

**Comment by ralphbean** [comment]
Nice!  Thanks for resolving this @cydrobolt!
