### ISSUE TITLE
Wiki user profile badge isn't being given

### ISSUE THREAD

**Issue by vwbusguy** [fedora-infra/tahrir#336]
Badge: https://badges.fedoraproject.org/badge/let-me-introduce-myself

Wiki Profile: https://fedoraproject.org/wiki/User:Vwbusguy

Badges page: https://badges.fedoraproject.org/user/vwbusguy

**Comment by nbebout** [comment]
Awarded.

**Comment by vwbusguy** [comment]
Many thanks!

**Comment by ghost** [comment]
Hello guys, I have the same issue with my account, I've create my page but the badge isn't awarded.

Wiki profile: https://fedoraproject.org/wiki/User:Carlosmorel

**Comment by sayanchowdhury** [comment]
Awarded the badge to @ghost
