### ISSUE TITLE
Wiki page edits badges not awarded

### ISSUE THREAD

**Issue by vwbusguy** [fedora-infra/tahrir#337]
Badges: https://badges.fedoraproject.org/badge/junior-editor , master, etc.

Wiki user contributions: https://fedoraproject.org/wiki/Special:Contributions/Vwbusguy

Badges page: https://badges.fedoraproject.org/user/vwbusguy

**Comment by vwbusguy** [comment]
Possibly related to #336

**Comment by vwbusguy** [comment]
My guess, which I haven't confirmed, is that there's a username mismatch with wiki due to case-sensitivity.  My wiki account is linked to FAS, but my FAS username is 'vwbusguy', where my wiki username is 'Vwbusguy' following older wiki nomenclature for names.

Link tom y wiki profile: https://fedoraproject.org/wiki/User:Vwbusguy
When I log in with my FAS (lowercase), the wiki cookie fpo-mediawiki_en_UserName shows "Vwbusguy" (note capital V)

The wiki badge gets the criteria from http://infrastructure.fedoraproject.org/infra/badges/rules/junior-editor.yml 

https://github.com/fedora-infra/fedbadges/blob/develop/fedbadges/rules.py apparently does a lookup for Nick in FAS or email in FAS, but doesn't appear to do a case-insensitive check, but it's hard for me to know further without server-side debugging.

**Comment by sayanchowdhury** [comment]
I see that there are few badges awarded for wiki edits. I am closing this issue. Feel free to open the issue, if you still have the issue.
