### ISSUE TITLE
OSCON 2015 Badge

### ISSUE THREAD

**Issue by vwbusguy** [fedora-infra/tahrir#338]
I am the "Scott Williams" mentioned in this article: http://fossforce.com/2015/07/oscon-expo-floor/

Excerpt:
"Then there were a couple of Scotts in the Fedora booth at the crack of, well, opening the expo hall at 9: Scott Suehle of Cumulus Networks — spouse of Raspberry Pi book author and Red Hat’s Community Team leader Ruth Suehle — was on hand to catch up in the Fedora booth, as well as Scott Williams, a long-time Fedora contributor and biblical scholar, when he’s not a DevOps engineer at Claremont McKenna College. "

My username is vwbusguy

**Comment by nbebout** [comment]
Awarded.

**Comment by vwbusguy** [comment]
Many thanks!
