### ISSUE TITLE
Represented Fedora at event not awarded

### ISSUE THREAD

**Issue by vwbusguy** [fedora-infra/tahrir#339]
Evidence:
https://fedoraproject.org/wiki/SCaLE_8x_Event
https://fedoraproject.org/wiki/SCALE_9X_Event
https://fedoraproject.org/wiki/SCALE_10X_Event
11,12, 13..
https://fedoraproject.org/wiki/SCaLE_14X_Event

https://fedoraproject.org/wiki/OSCON_2013
https://fedoraproject.org/wiki/Ohio_Linux_Fest_2008

I am "Scott Williams" (vwbusguy).

Here's my badges profile: https://badges.fedoraproject.org/user/vwbusguy

**Comment by vwbusguy** [comment]
Specifically, this badge: https://badges.fedoraproject.org/badge/the-panda-is-in

**Comment by pypingou** [comment]
You normally have to scan a QR code on site to be able to get the event's badge.

**Comment by vwbusguy** [comment]
I don't recall having that at SCaLE this year or in previous years.  I
thought I had at OSCON though.

**Comment by vwbusguy** [comment]
That said, the wiki links above show my participation at the Fedora both in
above events. Let me know if there's anything else I can provide (pictures,
articles, etc).

**Comment by ralphbean** [comment]
Hi!  Here's what you do:

- Go to the badge page:  https://badges.fedoraproject.org/badge/the-panda-is-in
- Look for the 'criteria' link.  Click it!
- That takes you to here:  https://fedorahosted.org/fedora-badges/ticket/250
- If you read the comment thread, you see that FAMSCo is in charge of awarding the badge:  https://fedorahosted.org/famsco/ticket/363
- And the person they have in charge of it is @nbebout.  So you could email him, or contact FAMSCo, or comment on the criteria ticket in the fedora-badges trac ticket.

Thanks!
