### ISSUE TITLE
White Rabbit - Timzeone FAS badge not awarded

### ISSUE THREAD

**Issue by vwbusguy** [fedora-infra/tahrir#340]
This looks like it's been previously reported at https://fedorahosted.org/fedora-badges/ticket/52 but wasn't actually fixed and affects my profile.

https://badges.fedoraproject.org/user/vwbusguy

I've also logged into FAS and tried resetting it, but doesn't seem to have any affect.

**Comment by ralphbean** [comment]
When I click the link to your profile page, I get a 404.  Is there a typo there?

**Comment by ralphbean** [comment]
Oh.  I see.

You disabled your badges account at some point in the past by clicking the Deactivate Account button on your badges profile page.

[That's why](https://github.com/fedora-infra/fedbadges/blob/develop/fedbadges/rules.py#L216-L221) you're not getting any badges.

Can you confirm?  If so, that should close #336, #338, #340, and #341.

**Comment by vwbusguy** [comment]
Odd, I've never disabled it on my end.

Scott

**Comment by vwbusguy** [comment]
Weird, it was 404 briefly this evening and now it shows deactivated. I
didn't deactivate it and you can see I had another badge today. I have no
idea what's going on.

Scott

**Comment by vwbusguy** [comment]
I can "reactivate" it but not sure if I should since I don't know what
caused it to be deactivated to begin with.

Scott

**Comment by vwbusguy** [comment]
At any rate, my account was active when these issues are reported. Please
do not close these tickets.

I'll reactivate the account, but it was active earlier when I filed these
and linuxmodder was looking at it on Irc.

Scott

**Comment by nbebout** [comment]
Awarded.

**Comment by sayanchowdhury** [comment]
The badge has been working now. I am closing this issue for now.
