### ISSUE TITLE
Badge Muse image has no margins

### ISSUE THREAD

**Issue by elioqoshi** [fedora-infra/tahrir#342]
The Badge Muse badge has no margins in the png. and is 223x223px big, instead of 256x256
https://badges.fedoraproject.org/badge/badge-muse-badges-released-i

**Comment by elioqoshi** [comment]
Here is the right file for the badge
![badgemuse_approved](https://cloud.githubusercontent.com/assets/5436686/13724348/bc0a94e8-e882-11e5-8a06-1ad0c254d59e.png)

**Comment by jflory7** [comment]
I think this issue actually affects all the badges in the series?

**Comment by elioqoshi** [comment]
Oh, it might be, I just noticed because I just received this badge. Justin is probably right

**Comment by ralphbean** [comment]
Can you re-file this issue over on https://fedorahosted.org/fedora-badges/ ?  I think the designers watch that tracker more closely and they'd be the ones to fix this.

**Comment by elioqoshi** [comment]
@ralphbean filed!
https://fedorahosted.org/fedora-badges/ticket/435

**Comment by ralphbean** [comment]
Thanks!
