### ISSUE TITLE
User ranking percentage is incorrectly displayed

### ISSUE THREAD

**Issue by dhgutteridge** [fedora-infra/tahrir#355]
Commit "(@sayanchowdhury) #328, fix the percentile for the top users in the leaderboard" from exactly a year ago introduced a couple of problems with the very thing it claimed to fix. Both are trivial to address, but the intent behind the change isn't entirely clear to me.

First of all, it's not correctly displaying the percentage value. For example, I'm currently ranked 2052 out of 43302 users. That would put me in the top 5%. However, the display says "top 0.05%" which is quite wrong: that would mean I'm ranked 23 or less out of 43302. The display is off by two orders of magnitude. When the change was made in tahrir/views.py, the "* 100" at the end of the calculation was lost.

Second, I don't follow why the precision was increased in tahrir/templates/user.mak to two decimal places when the code calculating the percentage rounds the result to a whole number -- when properly expressed as a percentage, that is. Saying someone's in the top 5.00% isn't too meaningful if the value is rounded. As other percentage values in the display are shown with one decimal place, I don't see the purpose here.

I'm happy to submit a git pull myself to address this, but I don't know if the intent is really to show a percentage value rounded to a whole number, or something with greater precision. I'm guessing the former. Either way, it's totally wrong right now.

**Comment by dhgutteridge** [comment]
Having looked over the pull request again, I see the comment says "Currently the top users in the leaderboard see (top 0.0%) instead it should be something like (top 0.01%)". So the intent would be to calculate to two decimal places. That means tahrir/templates/user.mak is correct, but tahrir/views.py needs to be fixed.

**Comment by dhgutteridge** [comment]
Pull request #356 submitted.

**Comment by sayanchowdhury** [comment]
Rightly saud, `* 100` was something that was lost. Before the change the problem was the top user would see their percentile as `top 0.0%`. Your PR looks good to me. I'll go ahead and merge.
