### ISSUE TITLE
Multiply awarded badges

### ISSUE THREAD

**Issue by bexelbie** [fedora-infra/tahrir#358]
Can the badges system support the idea of awarding the same badge to the same person multiple times?  I know we do that now with the series badges, like for blog posts.  Could we add some badges that just accumulate and show a number icon?

**Comment by sayanchowdhury** [comment]
Any example badge for which this would make sense?

**Comment by bexelbie** [comment]
Posting on Fedora Planet, for example, could have been implemented this way. There is also the possibility to count some other interactions for which the goal is not title oriented. I believe the functionality would see use. I am gathering from your response that it doesn't exist today. Is this correct?

**Comment by sayanchowdhury** [comment]
Yes, the feature does not exist.

**Comment by bexelbie** [comment]
Would this be a challenge to add?
