### ISSUE TITLE
Phoenix Down badge not awarded

### ISSUE THREAD

**Issue by morxa** [fedora-infra/tahrir#360]
I recently (a month ago) unretired [log4cxx](https://admin.fedoraproject.org/pkgdb/package/rpms/log4cxx/):
[re-review](https://bugzilla.redhat.com/show_bug.cgi?id=1408428)
[releng ticket](https://pagure.io/releng/issue/6575)
[devel announcement](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/BFM2L5VGBDAMW4URBTIPL726D7S42P7T/)

I wasn't awarded the [Phoenix Down](https://badges.fedoraproject.org/badge/phoenix-down) badge, cf. my [badges profile](https://badges.fedoraproject.org/user/thofmann).

I also noticed I'm not the only one, timfenn unretired [coot](https://admin.fedoraproject.org/pkgdb/package/rpms/coot/):
[re-review](https://bugzilla.redhat.com/show_bug.cgi?id=1359402)
[releng ticket](https://pagure.io/releng/issue/6615)
[devel announcement](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/CAAP3G6E2IW2WJ7QR2SUE2WMK2UTLYRM/#EE6UNJ6XWUZCR5UMEWVMWY3HZDDFQZVI)
[timfenn's badges profile](https://badges.fedoraproject.org/user/timfenn)

**Comment by morxa** [comment]
I just realized the last time this badge was ever awarded was on 2014-04-29 and it was only awarded 6 times. Is this badge not awarded anymore?

**Comment by sayanchowdhury** [comment]
The topic to which it listens to is no longer emitted. So the rule for the badges needs an update.

**Comment by haghighi-ahmad** [comment]
Same Issue
