### ISSUE TITLE
Anitya does not grand a badge

### ISSUE THREAD

**Issue by tydyt** [fedora-infra/tahrir#364]
I added several projects in Anitya (https://release-monitoring.org/) but the Telegraphist badge (https://badges.fedoraproject.org/badge/telegraphist-upstream-release-monitoring-i) wasn't granted.
As I can see, last one was granted on 30th September and nothing else since that time (I'm sure more people fulfilled the badge requirement since that time).
Infra team confirmed, they can see the fedmsg messages... but the badge didn't fire off.
This issue is linked to pagure issue at https://pagure.io/Fedora-Badges/issue/501

**Comment by haghighi-ahmad** [comment]
+1
Same issue
In past two weeks I edited several wiki pages, earned karma cookie and etc. But no badge earned.

**Comment by pes-soft** [comment]
+1 same issue here for the Telegraphist badge

**Comment by tydyt** [comment]
The [Telegraphist rule](https://pagure.io/Fedora-Badges/blob/master/f/rules/anitya-map-01.yml) triggers on events 
`anitya.project.map.new`

but instead of that,  there are only messages for events 
`org.release-monitoring.prod.anitya.project.map.new`

Could you try to adjust the condition rule to test if the new one will work please?

**Comment by cheese1** [comment]
+1
same issue

**Comment by bexelbie** [comment]
I've made this commit to try the fix suggested by @tydyt above https://pagure.io/fedora-badges/c/5bc0e317021b4a6cd8667036ca0c6fca4b6bb51c?branch=master

**Comment by bexelbie** [comment]
This fix didn't work because the agent string is no longer an email address.  We need to figure out how to tell the rule to convert this:

      "agent": "http://yselkowitz.id.fedoraproject.org/", 

Into a FAS ID.

**Comment by pypingou** [comment]
Take the piece between ``http://`` and `` id.fp.o``

**Comment by bexelbie** [comment]
@pypingou I agree.  I believe a function will be need to do this in the rules processor as I suspect that arbitrary code is not supported in the yaml file.

**Comment by bexelbie** [comment]
Following up, I think the function needs to be placed in https://github.com/fedora-infra/fedbadges/blob/2ac6398ab034c93c47222af48fced00dc383552e/fedbadges/rules.py#L40 and needs keys to have it activated, similar to email2fas.

WDYT?

**Comment by sayanchowdhury** [comment]
Yes, that's the place where the piece of code needs to be added. Maybe `agent2fas`

**Comment by bexelbie** [comment]
I've created a PR to add openid2fas here: https://github.com/fedora-infra/fedbadges/pull/59

I am not sure how to test this code.  Comments very appreciated.

**Comment by cheese1** [comment]
i could create another fedora-mappings to test that in production.
a "test" today: still no badges
the change seems to be not yet in production:
anitya.project.map.new -- cheese mapped the name of "Horde_Db" in Fedora to "php-horde-Horde-Db" https://release-monitoring.org/project/17391/

**Comment by cheese1** [comment]
badges are now granted again

**Comment by alcir** [comment]
Yesterday I mapped a couple of packages to release-monitoring.org, but I did not receive a badge

**Comment by cheese1** [comment]
https://badges.fedoraproject.org/badge/telegraphist-upstream-release-monitoring-i
states that badges are still granted
but maybe you would fal into the next category, which would be ready to get pushed to production:
https://pagure.io/Fedora-Badges/issue/357
