### ISSUE TITLE
Fedora Badges Ranking Percentage calculation errors

### ISSUE THREAD

**Issue by nariekalo** [fedora-infra/tahrir#367]
Ranking percentage calculations incorrect top 0.16% should read top 16%. Multiply by 100 final step in calculation missed decimal to precentage eg 7,243 of 45,407 is top 16% not top 0.16%.
Please double-check clarify. See Fedora Badges User Info Box.

**Comment by timhughes** [comment]
Looks like #356 has fixed this issue, it just isn't on the live server.

**Comment by nariekalo** [comment]
Good, thanks for letting me know.
