### ISSUE TITLE
JQuery should be minified

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/tahrir#369]
Every badge page includes `/resources/tw2.jquery/static/jquery/1.7.1/jquery.js`, which is not minified, and about ~243K. It could be reduced to ~92K or about 38% by using the minified version (based on code.jquery.com).

**Comment by pypingou** [comment]
Note that we'll still want to have the non-minified version in the repo likely

**Comment by sayanchowdhury** [comment]
We can probably go ahead and use `gulp`
