### ISSUE TITLE
Badge deletion script uses invalid SQL command, doesn't work

### ISSUE THREAD

**Issue by jflory7** [fedora-infra/tahrir#371]
_Originally filed at [pagure.io/fedora-infrastructure#6387](https://pagure.io/fedora-infrastructure/issue/6387)._

# Summary

The [`delete-badge` script](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/badges/backend/files/delete-badge) uses an invalid SQL statement since recent changes to [Tahrir](https://github.com/fedora-infra/tahrir) and will not delete an invalid badge.

# Stacktrace

From badges-backend01.phx2.fedoraproject.org.

```
$ sudo /usr/local/bin/delete-badge --badge fedora-women-day-attendee
deleting fedora-women-day-attendee
Failure: (ProgrammingError) relation "milestone" does not exist
LINE 2: FROM milestone 
             ^
 'SELECT milestone.id AS milestone_id, milestone.position AS milestone_position, milestone.badge_id AS milestone_badge_id, milestone.series_id AS milestone_series_id \nFROM milestone \nWHERE %(param_1)s = milestone.badge_id' {'param_1': u'fedora-women-day-attendee'}
```

# Analysis

There were a lot of changes made to Tahrir over the last few months, including the introduction of things like milestones and pathways for badges. It's likely the SQL statement isn't current based on the recent changes to upstream Tahrir.

cc: @sayanchowdhury

**Comment by sayanchowdhury** [comment]
Yes, this is something I too noticed while deleting the one of the badge. The migration was done but yet iirc but yet this popped up. This will be a priority once the freeze is over.

**Comment by sayanchowdhury** [comment]
The tables have been migrated. btw, @jflory7 did you delete this badge?

**Comment by justwheel** [comment]
@sayanchowdhury Thanks. Does this mean the CLI tools will work as expected now?

I think Kevin helped delete this one manually.

**Comment by sayanchowdhury** [comment]
@jflory7 Yes
