### ISSUE TITLE
Change Avatar takes me to Forbidden page on badges

### ISSUE THREAD

**Issue by suprith4989** [fedora-infra/tahrir#372]
![screenshot from 2017-09-27 15-26-08](https://user-images.githubusercontent.com/11404593/30907631-ac0a163c-a36a-11e7-8de3-6de489ee77d1.png)

**Comment by doctormo** [comment]
This looks like it was fixed in 97ab9d09fd4d6a632bf1139de637e70aa8cc9900 ref: https://bugs.launchpad.net/libravatar/+bug/1706984

**Comment by sayanchowdhury** [comment]
Fixed in #368
