### ISSUE TITLE
Bad percentage in ranking on users page

### ISSUE THREAD

**Issue by csonto** [fedora-infra/tahrir#374]
E.g. my [profile](https://badges.fedoraproject.org/user/mcsontos) says:

    Ranked 1447 out of 47144 ranked users (top 0.04%).

> I am a grand master! Top 0.04%, that's so cool!

But now my impostor syndrome asks me:

> Am I such a grand master?

And I must admit:

> I am not.

So there must be a bug. 1% out of 47144 is 471 people so it is approximately 2 orders of magnitude off. Seems it needs `*100` somewhere. 1447/47144 is 3.06%, so 0.0306 after rounding up a bit could be 0.04...

**Comment by CyrilStreit** [comment]
Agreement

**Comment by morxa** [comment]
See #367
