### ISSUE TITLE
Helping Hand wrongly awarded

### ISSUE THREAD

**Issue by morxa** [fedora-infra/tahrir#376]
I'm the owner/main admin of [sway](https://src.fedoraproject.org/rpms/sway), but nevertheless I was awarded the Helping Hand badge for submitting an update.

More info:
* [My badges profile](https://badges.fedoraproject.org/user/thofmann)
* [The event that got me the badge](https://apps.fedoraproject.org/datagrepper/id?id=2017-b1c533f6-99c2-40c5-9fc4-54d74491a5ed&is_raw=true&size=extra-large)

**Comment by mymindstorm** [comment]
Happened to me too. [Event](https://apps.fedoraproject.org/datagrepper/id?id=2018-503498d1-b632-46ab-9cee-1eea896f1624&is_raw=true&size=extra-large), [award](https://apps.fedoraproject.org/datagrepper/id?id=2018-a670f113-5f6d-4b07-b112-364bd19a42a8&is_raw=true&size=extra-large), [src](https://src.fedoraproject.org/rpms/numix-icon-theme-square)
