### ISSUE TITLE
Egg badge not awarded

### ISSUE THREAD

**Issue by pes-soft** [fedora-infra/tahrir#379]
Hi,

I'm on FAS for [more than a year](https://badges.fedoraproject.org/user/pessoft) ( around 20 months ), but I didn't receive the ["Egg" badge](https://badges.fedoraproject.org/badge/egg). However the badge is being awarded from time to time, so it is not completely stuck, maybe just skipped some accounts.

Thanks for checking it out.

**Comment by sayanchowdhury** [comment]
This could be a temporary issue. I am awarding you the badge manually.

**Comment by pes-soft** [comment]
Thanks ;)

Btw, I briefly compared holders of Baby Badger badge and Egg badge and a lot of Baby Badgers does not have the Egg, so I guess there are more people missing the badges related to the age of the FAS account.

**Comment by tydyt** [comment]
I"ve FAS account since 2013 and was granted with 3 years badge for the last time (in 2016). No further badge issued for my account since that time ( should get 5 and 7 years at least). These badges are still granted well not sure what's wrong with my account.

**Comment by mscherer** [comment]
Most FAS badges were broken because FAS got moved to openshift (and some firewall issue) and is now removed. However, for this one, this was fixed with https://pagure.io/fedora-infra/ansible/pull-request/444
