### ISSUE TITLE
Attempting to award a badge again should fail gracefully, not 500

### ISSUE THREAD

**Issue by stickster** [fedora-infra/tahrir#381]
If I attempt to award a badge to a person who already has it, I receive a 500 error. This operation should fail gracefully, either returning to the badge page with a failure notice, or a popup to that effect -- not a server internal error.

**Comment by abompard** [comment]
I don't seem to be able to reproduce it, I think this has been fixed a while ago without closing this issue. I'm closing it now, if you can reproduce it on your end, please reopen.
