### ISSUE TITLE
Migrate from Libravatar to another service (Gravatar?)

### ISSUE THREAD

**Issue by justwheel** [fedora-infra/tahrir#383]
Libravatar [announced this morning](https://blog.libravatar.org/posts/Libravatar.org_is_shutting_down_on_2018-09-01/) they are shutting down their service on 2018 September 1; this affects applications that use Libravatar, such as Pagure, Tahrir (Fedora Badges), and possibly others.

In their post, they mentioned they do not know of another FOSS image hosting service like Libravatar. If hosting images ourselves is not desired, Gravatar is the best viable alternative I know of.

This may deserve wider discussion since this issue affects multiple Fedora applications.

**Comment by ddreggors** [comment]
+1 Gravatar (if not hosted by Fedora)

**Comment by dadreggors** [comment]
Also, it seems that I cannot even change my avatar. I get a 403 ("CSRF verification failed. Request aborted.") error when clicking on  "Change Avatar".

**Comment by Zokormazo** [comment]
Finally fedora sponsored libravatar so no need to migrate, we can close this :)

**Comment by pypingou** [comment]
Agreed, let's close indeed :)
