### ISSUE TITLE
README: Unclear header hierarchy

### ISSUE THREAD

**Issue by jee1mr** [fedora-infra/tahrir#392]
All of the headers are at the same hierarchical level. It could be a bit confusing. For example, I initially thoughts these were the steps for setting up locally.
Building a configuration file -> Setting up the DB -> Running.

But it was actually supposed to be the "Hacking" header. Also, there are two "Hacking" headers. 

I think it should be structured better overall with proper hierarchy or a separate CONTRIBUTING.md.

**Comment by sayanchowdhury** [comment]
@jee1mr Let's start working on the docs. The README, in that case, can just have few lines like about the project, license etc. Anything more would be in the docs. Sounds good?

**Comment by jee1mr** [comment]
@sayanchowdhury Yup, that sounds good.
