### ISSUE TITLE
Badges not exportable to open badges

### ISSUE THREAD

**Issue by SilleBille** [fedora-infra/tahrir#398]
When a user clicks on "Export Badges" option, open badges sign in page pops up. After providing credentials and clicking on send, the pop up just says "no badges exported".

How often? Always
Actual expected : badges exported to open badges

**Comment by SilleBille** [comment]
Is there an update on this issue?

**Comment by cverna** [comment]
@SilleBille Hi I have just tried this and it worked as expected. Could you try again ?

**Comment by SilleBille** [comment]
@cverna thanks for looking into this. I was unable to export the badges. I have captured a small screen recording to demonstrate the issue: https://youtu.be/nblCudFv4UE

**Comment by cverna** [comment]
Ha I am not sure how to investigate that TBH. Also we are using beta.openbadges.org we should probably use just openbadges.org
