### ISSUE TITLE
As a Fedora Badges User I would like for badges to help motivate me to keep going, so that I learn the skills I want.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#404]
TBD.

#### Acceptance Criteria

**Comment by KyleRConway** [comment]
It would actually be kind of cool to have a choose-your-own-adventure sort of skill set increase map of some sort of like the old leveling up power sets in video games. In some ways, a badge framework that function like this could also work as a wonderful onboarding idea. It would allow you to create a pathway with badges associated for signing up for a fedora account, sending an email to apply to be part of the project, being assigned your first badge, signing the contract, etc etc etc. Think of it like missions for fedora but involving badges and gameification.
