### ISSUE TITLE
As an Individual Badge maintainer I need to have permission to revoke a badge if it was awarded by mistake

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#415]
TBD.

#### Acceptance Criteria

**Comment by justwheel** [comment]
A Python script for sysadmins to revoke badges exists in `ansible.git` [here](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/badges/backend/files/revoke-badge). Adding this functionality to the front-end specifically is valuable. Additionally, revoking a badge should (ideally) automatically award the [Consolation Prize badge](https://badges.fedoraproject.org/badge/consolation-prize) to someone. Currently the badge is awarded manually and by memory.

**Comment by sayanchowdhury** [comment]
@jwflory Rightly said, and you get a badge for that also if not awarded before.

**Comment by EUGINELETHAL** [comment]
![Screenshot from 2020-04-14 01:16:28](https://user-images.githubusercontent.com/25798915/79166354-a52afb00-7ded-11ea-868c-7abd15d8285f.png)
