### ISSUE TITLE
As a maintainer/designer I need timely help triaging badge request from the developer, so that I know which request can be implemented.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#417]
TBD.
#### Acceptance Criteria

**Comment by sayanchowdhury** [comment]
Do you mean maintainer/designer here?

**Comment by cverna** [comment]
How do we want to solve that ? How does the triage currently happen ? Do we need a meeting for the triage ?

@jwflory, @sayanchowdhury and @KyleRConway any ideas ?

**Comment by justwheel** [comment]
@cverna See [this comment](https://github.com/fedora-infra/tahrir/issues/423#issuecomment-487905942) in a previous issue for more context.

Currently, @riecatnor does all issue triage on the Fedora Badges repo. I am not personally involved with triage so I am not the best person to ask here.

**Comment by sayanchowdhury** [comment]
Right now there is no process involved around triaging other than @riecatnor doing the triage. I think that we should be starting to have a common meeting to see triage issues. @riecatnor already does a meeting, maybe we can join that and work?

Also, I've been thinking this for sometime now. Let's be strict fields the badge idea submitter needs to fill, that reduces a lot of burden.

**Comment by KyleRConway** [comment]
I've never been involved in triage formally. I've only been involved as a
designer awaiting feedback.
