### ISSUE TITLE
As a designer I would like to find an artwork ticket that I can implement so that I am contributing and not wasting time

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#421]
TBD.
#### Acceptance Criteria

**Comment by sayanchowdhury** [comment]
This one I think is similar to #423. It may be good to have a board with stages in which the issue is.

A lot of time I have seen the designer working on issues which are not possible/or yet not possible from tech side. I feel that it then becomes a ticket with the wasted effort from designer side.
