### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/tahrir#426]
Per [infra review](https://fedoraproject.org/wiki/Infrastructure_2020/Friday_with_Infra), this needs porting to Python 3. I made a desultory start on this today, I dunno how far I'll get with it, but [here is my branch](https://github.com/AdamWill/tahrir/tree/py3) so no-one duplicates the work I did so far at least. To get a dev env running currently you also need [this fix for tahrir-api](https://github.com/fedora-infra/tahrir-api/pull/47).

**Comment by AdamWill** [comment]
https://github.com/fedora-infra/tahrir/pull/427

**Comment by termdew** [comment]
Issue can be closed, as PR #427 is merged, no?

**Comment by laxathom** [comment]
Correct.
