### ISSUE TITLE
Can't export badges anymore

### ISSUE THREAD

**Issue by sandrobonazzola** [fedora-infra/tahrir#430]
Trying to export badges now shows in console:

```
Uncaught ReferenceError: OpenBadges is not defined
    at claim_badges
    at HTMLButtonElement.onclick
```
this is probably due to mozilla openbadges turned of on August 23rd 2019.
This makes problematic exporting badges to the new suggested platform at badgr.io.

**Comment by sandrobonazzola** [comment]
Anyone still looking at this issue tracker?

**Comment by mscherer** [comment]
I would say "likely no", as I did just see the ticket.  What instance did you use, can you tell a bit more ?
(I would assume Fedora, but prefer to double check)

**Comment by sandrobonazzola** [comment]
Yes, sorry, the instance is https://badges.fedoraproject.org/
I was trying to export my badges for importing them into the new backpack platform at https://eu.badgr.io
