### ISSUE TITLE
Unable to setup a development environment.

### ISSUE THREAD

**Issue by termdew** [fedora-infra/tahrir#431]
In the latest 'develop' branch i'm unable to create a developing environment according to DEVELOPING.md.

When i run `vagrant up`, it sets up the vm, and tries to run the inline script:

```
    default: Running: inline script
    default: Fedora Modular 30 - x86_64                      2.2 MB/s | 2.7 MB     00:01    
    default: Fedora Modular 30 - x86_64 - Updates            2.3 MB/s | 3.3 MB     00:01    
    default: Fedora 30 - x86_64 - Updates                    3.6 MB/s |  21 MB     00:05    
    default: Fedora 30 - x86_64                              7.8 MB/s |  70 MB     00:09    
    default: /tmp/vagrant-shell: line 1:  2687 Killed                  sudo dnf install -y libselinux-python python2-dnf
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
I think that somehow it runs into a timeout..

**Comment by termdew** [comment]
Turns out, that it was a memory overflow.
I fixed it by adding
`config.vm.provider :libvirt do |v|
    v.memory = 1024
  end` to the Vagrantfile, now the inline dnf setup process proceeds.

But now i have another issue:
The server complains, that it can't resolve a label reference.
it says: 
`  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 4556, in _no_text_coercion
    "extra": "%s " % extra if extra else "",
CompileError: Can't resolve label reference for ORDER BY / GROUP BY. Textual SQL expression 'count_1 desc' should be explicitly declared as text('count_1 desc')`

**Comment by laxathom** [comment]
You need the latest tahrir-api from develop branch which fixes this issue.
there also is a release on the way branch release/0.9.0.

**Comment by termdew** [comment]
I'm using the latest develop branch. Or am i missing some steps, which are not mentioned in the Developing Guide?

**Comment by laxathom** [comment]
How to did you set up your env?

**Comment by termdew** [comment]
I followed the DEVELOPING.md

1) cp Vagrantfile.example Vagrantfile
2) cp development.example.ini development.ini
2) vagrant up
3) vagrant ssh -c"cd /vagrant/; pserve --reload development.ini"

**Comment by laxathom** [comment]
Unfortunately, the vagrant setup grabs the current tahrir-api 0.8.x, which doesn't come w/ the fix.
You would need to build tahrir-api from branch develop and install it manually into your vagrant instance.

**Comment by termdew** [comment]
Okay, i will do that and create a PR with the workaround for the time being.

**Comment by ryanlerch** [comment]
this should be fixed now with using tiny-stage and the new varfgarnt setup.

need to update the docs, however..
