### ISSUE TITLE
update backpack js URL

### ISSUE THREAD

**Issue by SilleBille** [fedora-infra/tahrir#433]
Clicking on "Export Badges" throws the following error in the browser console:
![image](https://user-images.githubusercontent.com/8215572/67054156-951db180-f111-11e9-877c-c21d0a4d6c68.png)

The URL should point to: https://backpack.openbadges.org/issuer.js

PS: The openbadges in badges.fedoraproject.org still points to beta version of backpack. These need to be updated to the production URL.

**Comment by sandrobonazzola** [comment]
looks like a duplicate of #430

**Comment by SilleBille** [comment]
yes, that looks like a duplicate. Feel free to add required metadata and close the issue! :+1:
