### ISSUE TITLE
Running 'vagrant up' ends in 'ImportError'

### ISSUE THREAD

**Issue by joalon** [fedora-infra/tahrir#434]
Hi!

I'm getting ImportError: cannot import name 'ZopeTransactionExtension' from 'zope.sqlalchemy' (/usr/local/lib/python3.7/site-packages/zope/sqlalchemy/__init__.py) during the "initialize_tahrir_db development.ini" script when running vagrant up.

**Comment by joalon** [comment]
I think I found something, according to https://pypi.org/project/zope.sqlalchemy/ they renamed ZopeTransactionExtension to ZopeTransactionEvents in zope.sqlalchemy version 1.2, which was released 2019-10-17. I'll look into porting this

**Comment by ryanlerch** [comment]
The vagrant setup should work again now -- it uses tinystage infra -- we just need to update the docs to reflect this.\
