### ISSUE TITLE
Trivial: Umm... I've been awarded the Long Life to Pagure IV, V and III (in that order)

### ISSUE THREAD

**Issue by LyesSaadi** [fedora-infra/tahrir#440]
Hi !

I don't know if this is the proper place to file this bug, and I have no particular interest in tahrir (just that the e-mail notification I received was pretty funny :stuck_out_tongue:)... But [I've been awarded](https://badges.fedoraproject.org/user/lyessaadi) in a small interval (<1 minute) the awards Long Life to Pagure IV (150 commits), V (500 commits) and III (50 commits)...

I mean... I don't say that I don't have the ability to make 500 commits to Pagure in less than a minute and then retroactively remove 450 of them... But I don't :rofl:...

Either way, it was a funny issue to write and surely a once-in-a-century bug that will never end up happening again! And I'm honored to surely be the fastest Fedora contributor by making nearly 500 commits in less than a minute and the first to be awarded Long Life to Pagure V before receiving the Long Life to Pagure III :rofl:.

**Comment by mscherer** [comment]
yeah, this seems to happen on a regular basis, I do not know what cause that (could be some stg issue or something), but I do not have time to investigate right now.

**Comment by mscherer** [comment]
Closing this one, it was already reported on the badge repo: https://pagure.io/fedora-badges/issue/714
