### ISSUE TITLE
Wrong description in "I voted F32" badge

### ISSUE THREAD

**Issue by heis2201** [fedora-infra/tahrir#441]
https://badges.fedoraproject.org/badge/i-voted%3A-fedora-32

it says: 

_Participated in the Fedora 30 Elections!_, however, this is for the F32 term

**Comment by justwheel** [comment]
Hi @heis2201, could you please open this as a new issue on the Badges issue tracker?

https://pagure.io/fedora-badges

This repo is for the software that powers Fedora Badges. At the moment, badge metadata is not maintained here, but rather in the repo above :slightly_smiling_face:

**Comment by heis2201** [comment]
Sorry for this obvious mistake. Will re-file...

**Comment by justwheel** [comment]
Not obvious :grinning: Do you know how many repos we have for Badges? :joy: 

Thanks for your patience and re-filing!

**Comment by heis2201** [comment]
If this happens more frequently, I would say we could be more descriptive in the footer of the page, where both issue trackers (system and content) are linked. 
I'd be happy to submit a PR. Cheers!

**Comment by heis2201** [comment]
What do you think about https://github.com/fedora-infra/tahrir/pull/442?

Just an idea...
