### ISSUE TITLE
"Long live pagure IV" badge given for much fewer than 1000 commits on src.fp.o (not pagure)

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/tahrir#447]
I was looking at one of the package maintainers I've sponsored to see how they were getting on, and noticed that they'd received the "long live to pagure iv" badge, which is given to someone when they push 1000 commits to a pagure repository:

https://badges.fedoraproject.org/badge/long-life-to-pagure-pagure-vi

https://badges.fedoraproject.org/user/didiksupriadi41

I was quite happy to see them being this active, but wondered what repo they'd pushed 1000 commits to in such a short period of time.

The "for this activity" link goes to https://apps.fedoraproject.org/datagrepper/id?id=2021-490c648c-0afa-4417-b7aa-70829deeaeb9&is_raw=true&size=extra-large

On inspection, one sees that it's for the picoli package but there aren't 1000 commits there---not even 100. So there's something off with either the configuration of the badge, or the fedmsg bits that are triggering it:

https://src.fedoraproject.org/rpms/picocli/commits/rawhide

**Comment by sanjayankur31** [comment]
it isn't easy to push 1000 commits to a repo, so I suspect quite a few of us here on the list have received this badge incorrectly:

https://badges.fedoraproject.org/badge/long-life-to-pagure-pagure-vi

**Comment by mscherer** [comment]
Yes, this serie of badges get triggered by error from time to time, but I never looked why (and so never found why). Since people tend to be unhappy when they do not get badges, so I am not keen on removing badges for people.

**Comment by nphilipp** [comment]
That's why this badge exists: https://badges.fedoraproject.org/badge/consolation-prize

**Comment by sanjayankur31** [comment]
Ah, OK, as long as it's a known issue. 

If the issue is found, we can correct the list and give the necessary folks the consolation-prize badge, but I guess revoking badges isn't top priority for the community.

I was just a bit worried because it gives one the impression that someone has made 1000 commits to a repo, and on src.fp.o, that'll be something to worry about :laughing:

**Comment by nphilipp** [comment]
I think the verbal description of the badge is misleading: According to the [YAML](https://pagure.io/fedora-badges/blob/master/f/rules/pagure-long-life-1000.yml), the badge rule counts commits to any repo on Pagure, not to single ones. I'm not sure if the latter could even be expressed with the current rule syntax.

**Comment by sanjayankur31** [comment]
Ah, that makes sense. I was looking at opening a PR to correct the description, but it looks like there's a PR to drop the badge entirely:

https://pagure.io/fedora-badges/pull-request/806
