### ISSUE TITLE
Move from velruse to another library packaged in Fedora

### ISSUE THREAD

**Issue by mscherer** [fedora-infra/tahrir#451]
While moving tahrir to openshift, I noticed that one of the deps, velruse, is retired from Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1739641

It is python2 only: https://pypi.org/project/velruse/

This would block a python 3 port, from what I know.

The commit message of 17841107c00113e4aa7d97fe708e46f0f3b7bb53  point that the application is functional, so I guess velruse wasn't a big deal, so maybe it can just be removed.

**Comment by laxathom** [comment]
- [ ] Check impact on removing velruse usage

**Comment by mscherer** [comment]
So without velruse, we have no openid login. From here, there is at least 2 ways.
Porting the code to OIDC, (something like [this](https://github.com/ausecocloud/pyramid_oidc) but ideally, packaged, and at least, maintained (or looking like it is maintained)
Investigate if using https://github.com/fedora-infra/pyramid_fas_openid would work. It seems more maintained, but I do not know if it is used anywhere by Fedora. 

Do we have others pyramid applications linked to the fedora auth system ?

**Comment by mscherer** [comment]
Good news, bodhi is also a pyramid application, and maintained, so there is code for what we want.

**Comment by soh-123** [comment]
can you assign this to me please?

**Comment by ryanlerch** [comment]
Just pushed the code that migrates us to OIDC, and removes velruse as a dep.
