### ISSUE TITLE
Wrong FASJSON API calls

### ISSUE THREAD

**Issue by abompard** [fedora-infra/tahrir#453]
I'm seeing in the FASJSON logs some calls from the badges app with URLs such as:
`"GET /v1/users/https:/api.github.com/users/foobaruser/"`.
The URL is crafted by including the full github API url, where only the username should be included. FASJSON returns 404, obviously.
I know it's from the badges app because it's authenticated as `badges-backend`.

**Comment by ryanlerch** [comment]
@abompard i dont think this web frontend is doing any fasjson calls at the moment.

maybe it is the consumer?
