### ISSUE TITLE
FAS badges not working

### ISSUE THREAD

**Issue by ilippert** [fedora-infra/tahrir#454]
Hi, 
https://docs.fedoraproject.org/en-US/commops/outreach-badges/first-steps/ points me  to a couple of badges and how to receive these - but I do not see these as working:
https://badges.fedoraproject.org/badge/white-rabbit
https://badges.fedoraproject.org/badge/crypto-badger
https://badges.fedoraproject.org/badge/crypto-panda

I have described the trouble at https://pagure.io/fedora-join/Welcome-to-Fedora/issue/212#comment-772938

**Comment by mscherer** [comment]
All badges related to FAS are broken at the moment. It was broken first due to firewall issue, then because the whole system was changed (FAS v2 => IPA + nogging ).

**Comment by murphnj** [comment]
It's strange, I've gotten "Community Survey Taker" and "Fedora 36 Release Party" recently, but badges for "Kernel Tester" have not been awarded (for me at least)
Not sure if this is the same problem, or if I should file a separate bug.  Any advice?

**Comment by mscherer** [comment]
Seems to be a separate issue. The badge was last warded not so long ago, so I guess a issue on the bus.

**Comment by laxathom** [comment]
> Seems to be a separate issue. The badge was last warded not so long ago, so I guess a issue on the bus.

I second that. (replied on the ticket you opened)

**Comment by laxathom** [comment]
> All badges related to FAS are broken at the moment. It was broken first due to firewall issue, then because the whole system was changed (FAS v2 => IPA + nogging ).

@mscherer is the new system trigger/send the msg to the bus so it can be awarded?

**Comment by murphnj** [comment]
I have to claim a bit of ignorance, I created a new issue from that comment, not sure what "the bus" is.

**Comment by mscherer** [comment]
@laxathom no idea, but fedmsg was busy crashing, so i restarted and cleaned the queue

**Comment by murphnj** [comment]
Have they finished processing?  Is there anything I can do from this end?

**Comment by mscherer** [comment]
The processing have been likely done. However, the message could have been lost and would be triggered for next kernel run (I think, I am not familliar with that badges)

**Comment by murphnj** [comment]
> The processing have been likely done. However, the message could have been lost and would be triggered for next kernel run (I think, I am not familliar with that badges)

Thanks for the response, I'll follow up when I participate in the next round of Kernel tests.

**Comment by murphnj** [comment]
It's been quite a while, and I've done another round of kernel tests, and still no new badges.  I've gotten the emails that they have run "murph ran a test of 5.19.1-300.fc36.x86_64 (PASS)" but still nothing.  Is there something else I need to do?
