### ISSUE TITLE
It's strange, I've gotten "Community Survey Taker" and "Fedora 36 Release Party" recently, but badges for "Kernel Tester" have not been awarded (for me at least)

### ISSUE THREAD

**Issue by murphnj** [fedora-infra/tahrir#459]
It's strange, I've gotten "Community Survey Taker" and "Fedora 36 Release Party" recently, but badges for "Kernel Tester" have not been awarded (for me at least)
Not sure if this is the same problem, or if I should file a separate bug.  Any advice?

_Originally posted by @murphnj in https://github.com/fedora-infra/tahrir/issues/454#issuecomment-1155882260_

Just for reference, I ran the script with my credentials, and I have many email notifications showing that the tests ran.  I can provide details if needed.

**Comment by laxathom** [comment]
Which script have you ran?

**Comment by murphnj** [comment]
The one on the kerneltest .iso file. "sudo ./runtests.sh"  All of the tests I ran were from booting off of the kerneltest .iso
I create a .config file from the supplied sample, set to "authenticated", and put my username and password in the script.  Seems like they worked, since I got the notification emails:
"murph ran a test of 5.18.1-200.fc36.x86_64 (PASS)"

**Comment by penguinpee** [comment]
Please report issues with badges on [Pagure](https://pagure.io/fedora-badges).
