### ISSUE TITLE
Outdated info on /about in prod (wrong branch?)

### ISSUE THREAD

**Issue by icesvz** [fedora-infra/tahrir#465]
Theres wrong link on https://badges.fedoraproject.org/about page.

As i see the page used "fedora" branch 
https://github.com/fedora-infra/tahrir/blob/fedora/fedora-sitedocs/about.rst 
as a source for that page but the data is 10 years old and incorrect. 

The default "develop" branch is fine and should be used as source, imho. 
https://github.com/fedora-infra/tahrir/blob/develop/fedora-sitedocs/about.rst

**Comment by ryanlerch** [comment]
This is fixed in trunk now, will be updated when badges is next updated.
