### ISSUE TITLE
Display user avatars using their actual email adress

### ISSUE THREAD

**Issue by abompard** [fedora-infra/tahrir#482]
In the Badges system, everybody's "email" address is fasusername@fp.o, because users are keyed on email addresses and not nicknames. But FAS has the actual email address that a user may have set their libravatar on.
Tahrir should ask FASJSON what the user's actual email address is to build the libravatar URL. This request should be cached for a reasonable amount of time (or, to be fancier, invalidated by fedbadges when a FAS message comes in about a user changing their email address).

**Comment by abompard** [comment]
Another way would be to cache the email address when the user logs in to Tahrir, because it's available in the profile that Ipsilon gives us.
When changing it in Noggin they'd have to login to Tahrir again to see it updated (or maybe a fedora-messaging consumer could update that automatically).

**Comment by abompard** [comment]
For the record, in the previous version, the user's avatar was resulting from a query to libravatar with their openid identifier. That's not good either.

**Comment by abompard** [comment]
Done in 64c3abc69de60c728f51312568a0ab7f5c8e86c9

**Comment by penguinpee** [comment]
Thanks a lot! The front page looks way more familiar now. :star_struck:
