### ISSUE TITLE
Badges link are not working anymore

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/tahrir#494]
Some users are reporting that links for claiming badges are not working anymore. It's most visible at `I voted: Fedora 40` badge.
![image](https://github.com/fedora-infra/tahrir/assets/6943409/e9f48b99-46cf-4764-92eb-73105cac8a3a)

**Comment by penguinpee** [comment]
Please not that the current link in the voting app is not a claim link. It goes directly to the landing page of the badge, which is wrong.

I sent Aoife a claim link, which is done by creating an invitation on the Badges page. Option is available to admins and people authorized for a certain badge.

**Comment by Zlopez** [comment]
Just to clarify this, the link used in elections app is not generated from badges app?

**Comment by penguinpee** [comment]
Correct. It has been copied from the landing page of the badge I assume.

**Comment by Zlopez** [comment]
Ok, I'm closing this then as it's not a problem of the app.

**Comment by penguinpee** [comment]
There is an issue, however, with sending invitations. They never arrive. I pinged @abompard about it on Matrix. But it's probably worth opening a ticket for that.

**Comment by abompard** [comment]
Hi! Could you give more details please? When did you send the invitation precisely? (Or do it again if possible) I'll have a look at the logs but I don't see any obvious traceback for that at the moment.

Also, Matrix is unreliable for that (and for me), I sometimes see that I have been pinged and sometimes not :shrug: (especially if I was away when the ping happened).

**Comment by abompard** [comment]
Oops wrong ticket.
