### ISSUE TITLE
Badges invitations are not sent / claim links created by authorized users don't work

### ISSUE THREAD

**Issue by penguinpee** [fedora-infra/tahrir#495]
For claim links authorized users or admins need to create invitations. Those are e-mailed to a user and contain a QR-code and a URL. I created an invitation for Aoife this morning for the _I voted: Fedora 40_ badge, but she never received it.

I also tried to send one to myself on two different addresses. Neither arrived.

**Comment by abompard** [comment]
Hi! Could you give more details please? When did you send the invitation precisely? (Or do it again if possible) I'll have a look at the logs but I don't see any obvious traceback for that at the moment.

Also, Matrix is unreliable for that (and for me), I sometimes see that I have been pinged and sometimes not :shrug: (especially if I was away when the ping happened).

**Comment by penguinpee** [comment]
I suppose you have admin access to Badges. If so, you can help yourself. Just create an invitation for any badge using your e-mail address.

The first invitation, sent to Aoife's RH address, was created around 07:45 UTC. The second attempt, sending to myself, took place around 09:25 UTC.

**Comment by abompard** [comment]
Also, do you have an example of the email that was sent please? I'm not finding in the code where that's supposed to happen.

**Comment by hroncok** [comment]
I wonder. Could we manually share a claim link with Aoife instead of trying to make this invitation thing work?

**Comment by penguinpee** [comment]
I don't have an example myself. I don't use that functionality myself often. But the code is in `app.py`, I believe: https://github.com/fedora-infra/tahrir/blob/dc8e3453552007257ef658990e5d24daadf6d31d/tahrir/app.py#L20

**Comment by penguinpee** [comment]
> I wonder. Could we manually share a claim link with Aoife instead of trying to make this invitation thing work?

That's what I tried to achieve with the invitation. I don't know of any other way creating claim links. But if there is, that will work.

**Comment by penguinpee** [comment]
Found it! On the badges page itself. It seems creating an invitation also creates a claim link on the ~~badge~~ profile page one has been invited to. I'll send that to Aoife.

**Comment by hroncok** [comment]
1. go to https://badges.fedoraproject.org/admin
 2. scroll to *Create Authorizations*
 3. input `i-voted:-fedora-40` to Badge ID, input your @fedoraproject.org email address to Person Email (or input Aoife's)
 4. got to https://badges.fedoraproject.org/badge/i-voted:-fedora-40 (or Aoife goes there)
 5. in *Award this badge*, use *Create invitation* with a reasonable expiration date
 6. the app redirects you to your profile, on the left, see *Active Invitations*

**Comment by hroncok** [comment]
also apparently, when you "send Invitations", it also appears on the user profile of the recipient

**Comment by hroncok** [comment]
however, when I then try to claim the badge via the provided link, the app says I have received the badge, but nothing seems to indicate that I actually have received it

**Comment by penguinpee** [comment]
> however, when I then try to claim the badge via the provided link, the app says I have received the badge, but nothing seems to indicate that I actually have received it

That could be a bug. I vaguely remember someone reported issues with claim links earlier, after Badges was moved to RHEL9 on OpenShift. @jwflory might know more.

> 4\. got to https://badges.fedoraproject.org/badge/i-voted:-fedora-40 (or Aoife goes there)

I granted myself authorization on the badge. But I do not see any link for awarding it. Maybe that's something conflicting with being logged in as an admin? Anyway, I sent Aoife the link and told her where to find it herself. But if that results in

> however, when I then try to claim the badge via the provided link, the app says I have received the badge, but nothing seems to indicate that I actually have received it

it will not solve the issue.

**Comment by abompard** [comment]
> however, when I then try to claim the badge via the provided link, the app says I have received the badge, but nothing seems to indicate that I actually have received it

Huh, yeah, the piece of code that awards the badge is somehow commented out. I'll fix it now.

**Comment by abompard** [comment]
Fixed.

**Comment by abompard** [comment]
So the nominal process with invitations is apparently that setting them in the admin UI will add a claim & qrcode link to the profile of the user whose email address has been set on creation. By the way, make sure you get that email right: if the email doesn't exist already in the database, tahrir-api will select a random user and use that for the invitation (!). I'll open a ticket for that.

**Comment by penguinpee** [comment]
> So the nominal process with invitations is apparently that setting them in the admin UI will add a claim & qrcode link to the profile of the user whose email address has been set on creation. By the way, make sure you get that email right: if the email doesn't exist already in the database, tahrir-api will select a random user and use that for the invitation (!).

Am I understanding this correctly? The field _Person email_ needs to be one of those pseudo e-mail address (fas@fp.o) like when authorizing users? That would explain at least two of my invitations not being sent out.

I think we should eventually change the name of that field or add some inline help. It has been confusing me from day one.

Anyway, thanks for fixing it. At least the voting can proceed (be restarted) with a working link.

There be :dragon:<sub>s</sub> (and :snake:<sub>s</sub>)

**Comment by abompard** [comment]
> Am I understanding this correctly? The field _Person email_ needs to be one of those pseudo e-mail address (`fas@fp.o`) like when authorizing users?

Correct, that's also what I understand from the code. This field is auto-filled when the invitation creation is not done by an admin, but when admins create invitations it has to be one of those pseudo email-addresses.

> That would explain at least two of my invitations not being sent out.

Also, I don't think any invitations are actually sent out as emails, they only appear on the user's profile.

> I think we should eventually change the name of that field or add some inline help. It has been confusing me from day one.

Indeed.

**Comment by penguinpee** [comment]
Thanks for the clarification. At least it's written down now, so I can circle back here, when my ageing :brain: let's me down again.

**Comment by oersen** [comment]
When I click the claim link, I got the below error:

```
410 Gone
This resource is no longer available. No forwarding address is given.

That invitation is expired. 
```

**Comment by penguinpee** [comment]
We are aware of the issue. I'm currently trying to find out if that is due to a user error (no expiration date set; defaults to two hours) or if something else is wrong (read: a bug in Tahrir).

**Comment by abompard** [comment]
Now that the app has been ported to Flask, I've changed the field label to be clearer and also made it accept just usernames, not the entire pseudo-email address:

![image](https://github.com/fedora-infra/tahrir/assets/95780/def0e975-f648-4a71-a6c2-1bea2e17e1cb)
