### ISSUE TITLE
Wrong image URL for badge

### ISSUE THREAD

**Issue by penguinpee** [fedora-infra/tahrir#497]
When I add new recurring event badges, I usually open the image of a previous badge and modify the URL accordingly. Doing so for DevConf.cz, I openend the image for [DevConf.cz 2023](https://badges.fedoraproject.org/badge/devconf.cz-2023-attendee) with right click and open image in new tab.

The image URL turned out to be https://infrastructure.fedoraproject.org/infra/badges/pngs/dev-conf-cz-attendee-2023.png when it should be https://badges.fedoraproject.org/pngs/dev-conf-cz-attendee-2023.png. The image is available in both locations. However, the newly uploaded images for DevConf.cz 2024 and 2025 are only available on https://badges.fedoraproject.org/pngs/dev-conf-cz-attendee-2025.png and https://badges.fedoraproject.org/pngs/dev-conf-cz-attendee-2025.png respectively.

It seems something went wrong when creating the 2023 badge and that should probably be fixed in the database. Before Badges moved to OpenShift, I could use a script on badges-backend01 to fix the issue myself. I'm not sure how to do that now. There might be more such cases. Finding them all would require a database query on image URLs.

**Comment by abompard** [comment]
Done, thanks for the report!
