### ISSUE TITLE
libravatar profile pic not synced to Fedora account

### ISSUE THREAD

**Issue by boredsquirrel** [fedora-infra/tahrir#500]
I have no idea why we need this external service just for hosting a picture...

But I created a libravatar account with the same name and address as on fedora, from the  fedora accounts page. They should be linked.

Still, the profile pic is not synced.

**Comment by abompard** [comment]
Hey! What's your Fedora username? I'll check this out.

**Comment by penguinpee** [comment]
zodbot tells me we have a FAS user with the same user name as the reporter: boredsquirrel. :chipmunk:

**Comment by abompard** [comment]
Is this you @boredsquirrel : https://badges.fedoraproject.org/user/boredsquirrel
I do see a picture, is it not the right one?

**Comment by boredsquirrel** [comment]
Okay that seems to have been fixed. Thank you guys!
